DROP TABLE IF EXISTS student;
CREATE TABLE IF NOT EXISTS student(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(500) NOT NULL UNIQUE,
    dob DATE,
    phone BIGINT NOT NULL,
    marks REAL CHECK (marks >= 0 AND marks <= 100),
    is_married BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);