"""add column to database

Revision ID: 3ec39da0f43d
Revises: 9b7ce5ceeb3f
Create Date: 2025-08-25 11:16:34.088905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec39da0f43d'
down_revision: Union[str, Sequence[str], None] = '9b7ce5ceeb3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('is_white_turn', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'is_white_turn')
    # ### end Alembic commands ###
